version: '3.8'

services:
  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Standard RabbitMQ Port (für Producer/Consumer)
      - "15672:15672"  # Management UI Port (zur Überwachung)
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user

  # MongoDB Instances
  mongo1:
    image: mongo:4.4
    container_name: mongo1
    ports:
      - "27017:27017"
    command: --replSet rs0 --bind_ip_all
    networks:
      - mongo_cluster

  mongo2:
    image: mongo:4.4
    container_name: mongo2
    command: --replSet rs0 --bind_ip_all
    networks:
      - mongo_cluster

  mongo3:
    image: mongo:4.4
    container_name: mongo3
    command: --replSet rs0 --bind_ip_all
    networks:
      - mongo_cluster

  # Consumer für MSFT
  consumer-msft:
    image: simonchhit/consumer:latest
    container_name: consumer-msft
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_QUEUE: MSFT
      MONGODB_URI: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0
      MONGODB_DATABASE: finance
      MONGODB_COLLECTION: aggregated_prices
    depends_on:
      - rabbitmq
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongo_cluster

  # Consumer für TSLA
  consumer-tsla:
    image: simonchhit/consumer:latest
    container_name: consumer-tsla
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_QUEUE: TSLA
      MONGODB_URI: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0
      MONGODB_DATABASE: finance
      MONGODB_COLLECTION: aggregated_prices
    depends_on:
      - rabbitmq
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongo_cluster

  # Consumer für AAPL
  consumer-aapl:
    image: simonchhit/consumer:latest
    container_name: consumer-aapl
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_QUEUE: AAPL
      MONGODB_URI: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0
      MONGODB_DATABASE: finance
      MONGODB_COLLECTION: aggregated_prices
    depends_on:
      - rabbitmq
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongo_cluster

  # Frontend
  frontend:
    image: simonchhit/frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    environment:
      MONGODB_URI: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0
      MONGODB_DATABASE: finance
      MONGODB_COLLECTION: aggregated_prices
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongo_cluster

networks:
  mongo_cluster:
    driver: bridge
