# Dockerfile-tsla-aapl-mfst für Kunde A
FROM python:3.9-slim

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt

ENV MONGODB_URI=mongodb://localhost:27018
ENV MONGODB_DATABASE=finance
ENV MONGODB_COLLECTION=aggregated_msft
ENV RABBITMQ_HOST=localhost
ENV RABBITMQ_QUEUE=MSFT
ENV BATCH_SIZE=1000

CMD ["python", "consumer.py"]
